name: "Styleguide - James Fenn"
description: "James Fenn's personal styleguide"
url: "/styles"
baseurl: "/"
giturl: "https://jfenn.me/redirects/?t=github&d=styles"

collections:
    elements:
        output: true
    categories:
        output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
    sass_dir: ./css
