name: "Styleguide - James Fenn"
description: "James Fenn's personal styleguide"
url: https://jfenn.me/styles
baseurl: "/"

collections:
    elements:
        output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
    sass_dir: ./css
